version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: team-project-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: team-project-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/team_project_db
      JWT_SECRET: supersecretkey
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: team-project-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: